### ISSUE TITLE
Also map the dependencies of stdlibs

### ISSUE THREAD

**Issue by IanButterworth** [JuliaPackaging/HistoricalStdlibVersions.jl#9]
We currently only store a julia version to stdlib map, but the deps of the stdlibs themselves also need to be resolved afaik.

@KristofferC has talked about this before. I don't fully understand what is needed both here and in Pkg to handle this

cc. @giordano @staticfloat

**Comment by KristofferC** [comment]
> I don't fully understand what is needed both here and in Pkg to handle this

For a given stdlib and a given julia version we need the set of deps (+ weakdeps) to inject here: https://github.com/JuliaLang/Pkg.jl/blob/d1f91fd37111aacd056a99b5f8c9315b578ae285/src/Operations.jl#L523C15-L540 instead of looking at the project file for the stdlib bundled with the current Julia.

**Comment by IanButterworth** [comment]
Would a correct way to do this be to just get the required version julia exe (via juliaup?) and query it as a subprocess for the list?

I don't think we need this lookup to be really fast?
